### ISSUE TITLE
no XPrv::normalize_bytes

### ISSUE THREAD

**Issue by islishude** [typed-io/rust-ed25519-bip32#3]
https://github.com/typed-io/rust-ed25519-bip32/blob/5cb04a6ac5f19bbe4908b35af6d9f860420a61b9/src/bench.rs#L5

no function or associated item named `normalize_bytes` found for struct `key::XPrv` in the current scope
function or associated item not found in `key::XPrv`

**Comment by vincenthz** [comment]
thanks, I've fixed it
